//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminID { get; set; }
        public string admin_pass { get; set; }
        public string admin_username { get; set; }
        public string admin_mail { get; set; }
    }
}
