//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Freelancer()
        {
            this.ApplyJobs = new HashSet<ApplyJob>();
            this.Hires = new HashSet<Hire>();
            this.Payments = new HashSet<Payment>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int freelancerID { get; set; }
        public string freelancer_username { get; set; }
        public string freelancer_pass { get; set; }
        public string freelancer_phone { get; set; }
        public Nullable<int> freelancer_stat { get; set; }
        public Nullable<double> freelancer_rating { get; set; }
        public string freelancer_mail { get; set; }
        public string freelancer_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyJob> ApplyJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hire> Hires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
