//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoiceID { get; set; }
        public Nullable<int> paymentID { get; set; }
        public double pricing { get; set; }
        public string details { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
