//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jobs4youEntities1 : DbContext
    {
        public Jobs4youEntities1()
            : base("name=Jobs4youEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplyJob> ApplyJobs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Freelancer> Freelancers { get; set; }
        public virtual DbSet<Hire> Hires { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
    }
}
