//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int paymentID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> jobID { get; set; }
        public Nullable<int> clientPayStat { get; set; }
        public Nullable<int> freelancerID { get; set; }
        public double amount { get; set; }
        public Nullable<int> frlncrReceiveStat { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Freelancer Freelancer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual job job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
