//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4You.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int skillID { get; set; }
        public int freelancerID { get; set; }
        public string skills { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
    }
}
